env:
  - GRAPHIQL_URI='http://localhost:8080/static/graphiql'
language: python
services: docker
python:
  - 3.5
before_install:
  - docker run -d -p8080:80 huygensing/timbuctoo:v6.16
  - python -m dsim.connection "$GRAPHIQL_URI" 8
script:
  - python -m pytest test/test_connection.py
