version: '2.1'

services:
  timbuctoo:
    image: huygensing/timbuctoo
    command: sh -c "if ! [ -f /mapped-data/auth/users.json ]; then mkdir -p /mapped-data/auth; echo '[]' > /mapped-data/auth/users.json; fi; if ! [ -f /mapped-data/auth/logins.json ]; then mkdir -p /mapped-data/auth; echo '[]' > /mapped-data/auth/logins.json; fi; /app/bin/timbuctoo server /app/example_config.yaml"
    environment:
      timbuctoo_elasticsearch_host: http://elasticsearch
      timbuctoo_elasticsearch_port: 9200
      base_uri: http://localhost:8080
      JAVA_OPTS: ${JAVA_OPTS}
      timbuctoo_dataPath: ${timbuctoo_dataPath:-/mapped-data}
      timbuctoo_authPath: ${timbuctoo_authPath:-/mapped-data/auth}
    volumes:
      - ./timbuctoo-data/:/mapped-data
    ports:
      - 8080:80
      - 8081:81
